package com.porfiriopartida.timetracking.ui.components.panels;

import javax.swing.*;
import java.awt.*;

public class ApplicationRow extends JPanel {
    private JPanel applicationRowPanel;
    private JProgressBar appProgress;
    private JLabel appLabel;
    private JLabel hmsLabel;
    public long timeValue;

    public JProgressBar getAppProgress() {
        return appProgress;
    }

    public void setAppProgress(JProgressBar appProgress) {
        this.appProgress = appProgress;
    }

    public long getTimeValue() {
        return timeValue;
    }

    public void setTimeValue(long timeValue) {
        this.timeValue = timeValue;
    }

    public ApplicationRow() {
        appProgress.setMaximum(100);
        add(applicationRowPanel);
    }

    public void setAppName(String appName) {
        appLabel.setText(appName);
    }
//
//    public void setAppProgress(int n){
//        appProgress.setValue(n);
////        appProgress.repaint();
//    }

    public JPanel getApplicationRowPanel() {
        return applicationRowPanel;
    }

    public void setApplicationRowPanel(JPanel applicationRowPanel) {
        this.applicationRowPanel = applicationRowPanel;
    }

    public void setAppLabel(JLabel appLabel) {
        this.appLabel = appLabel;
    }

    public JLabel getAppLabel() {
        return this.appLabel;
    }

    public JLabel getHmsLabel() {
        return hmsLabel;
    }

    public void setHmsLabel(JLabel hmsLabel) {
        this.hmsLabel = hmsLabel;
    }

    public void refresh() {
        revalidate();
        repaint();
        applicationRowPanel.revalidate();
        applicationRowPanel.repaint();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /** Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        applicationRowPanel = new JPanel();
        applicationRowPanel.setLayout(new GridBagLayout());
        applicationRowPanel.setMinimumSize(new Dimension(326, 24));
        applicationRowPanel.setOpaque(true);
        appLabel = new JLabel();
        appLabel.setEnabled(true);
        appLabel.setHorizontalAlignment(2);
        appLabel.setHorizontalTextPosition(2);
        appLabel.setText("{APPLICATION_NAME}");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        applicationRowPanel.add(appLabel, gbc);
        hmsLabel = new JLabel();
        hmsLabel.setEnabled(true);
        hmsLabel.setHorizontalAlignment(2);
        hmsLabel.setHorizontalTextPosition(2);
        hmsLabel.setText("00:00:00");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 5, 0, 5);
        applicationRowPanel.add(hmsLabel, gbc);
        appProgress = new JProgressBar();
        appProgress.setValue(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 5);
        applicationRowPanel.add(appProgress, gbc);
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return applicationRowPanel;
    }

}
