package com.porfiriopartida.timetracking.ui.components.panels;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class ApplicationRow extends JPanel {
    private JPanel applicationRowPanel;
    private JProgressBar appProgress;
    private JLabel appLabel;
    public long timeValue;

    public JProgressBar getAppProgress() {
        return appProgress;
    }

    public void setAppProgress(JProgressBar appProgress) {
        this.appProgress = appProgress;
    }

    public long getTimeValue() {
        return timeValue;
    }

    public void setTimeValue(long timeValue) {
        this.timeValue = timeValue;
    }

    public ApplicationRow() {
        appProgress.setMaximum(100);
        add(applicationRowPanel);
    }

    public void setAppName(String appName) {
        appLabel.setText(appName);
    }
//
//    public void setAppProgress(int n){
//        appProgress.setValue(n);
////        appProgress.repaint();
//    }

    public JPanel getApplicationRowPanel() {
        return applicationRowPanel;
    }

    public void setApplicationRowPanel(JPanel applicationRowPanel) {
        this.applicationRowPanel = applicationRowPanel;
    }

    public void setAppLabel(JLabel appLabel) {
        this.appLabel = appLabel;
    }

    public JLabel getAppLabel() {
        return this.appLabel;
    }

    public void refresh() {
        revalidate();
        repaint();
        applicationRowPanel.revalidate();
        applicationRowPanel.repaint();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /** Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        applicationRowPanel = new JPanel();
        applicationRowPanel.setLayout(new GridLayoutManager(1, 3, new Insets(10, 10, 10, 10), -1, -1));
        applicationRowPanel.setMinimumSize(new Dimension(326, 24));
        applicationRowPanel.setOpaque(true);
        applicationRowPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        appLabel = new JLabel();
        appLabel.setEnabled(true);
        appLabel.setHorizontalAlignment(2);
        appLabel.setHorizontalTextPosition(2);
        appLabel.setText("{APPLICATION_NAME}");
        applicationRowPanel.add(appLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        appProgress = new JProgressBar();
        appProgress.setValue(0);
        applicationRowPanel.add(appProgress, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return applicationRowPanel;
    }

}
